robot_base_frame: body

transform_tolerance: 0.5

# robot_radius: 0.30
inflater:
  # robot_radius: 0.30
  inflation_radius: 0.20

obstacles:
  observation_sources: base_scan
  base_scan:
    data_type: LaserScan
    topic: base_scan
    sensor_frame: body
    marking: true
    clearing: true
    obstacle_range: 4.0
    raytrace_range: 5.0
    # min_obstacle_height: 0.25
    # max_obstacle_height: 0.3
    min_obstacle_height: 0.1
    max_obstacle_height: 0.5
  z_voxels: 16
  z_resolution: 0.125
  max_obstacle_height: 2.0
