robot_base_frame: body

# Set this value larger if 'Costmap2DROS transform timeout' occurs
transform_tolerance: 1.0 # default: 0.5

inflater:
  inflation_radius: 0.20

obstacles:
  observation_sources: base_scan
  base_scan:
    data_type: LaserScan
    topic: base_scan
    sensor_frame: body
    marking: true
    clearing: true
    obstacle_range: 4.0
    raytrace_range: 5.0
    min_obstacle_height: 0.1
    max_obstacle_height: 1.0
  z_voxels: 16
  z_resolution: 0.125
  max_obstacle_height: 2.0
