# Planner selection
base_global_planner: "navfn/NavfnROS"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"

# Recovery behaviors are defined in robot folders

# Oscillation
oscillation_timeout: 10.0
oscillation_distance: 0.5

# Global planner
planner_frequency: 0.0
planner_patience: 5.0
NavfnROS:
  allow_unknown: true  # TODO: investigate this
  default_tolerance: 0.0
  cost_factor: 5
  neural_factor: 5
  # do not restrict planner
  planner_window_x: 0.0
  planner_window_y: 0.0
  # debug
  visualize_potential: false

# Local planner
controller_frequency: 25.0
controller_patience: 15.0
TrajectoryPlannerROS:
  # base vel/accel profile is in robot folders
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  # slow spot speed for safety
  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_y: 0.3
  min_vel_y: 0.0
  max_vel_theta: 0.7
  min_vel_theta: -0.7

# Recovery behaviors
recovery_behavior_enabled: true
recovery_behaviors:
  # do not use rotate_recovery because spot is not round shape
  - name: "conservative_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
  - name: "aggressive_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
conservative_reset:
  reset_distance: 3.0
aggressive_reset:
  reset_distance: 3.0
